version: "3.8"

services:
  footbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8022:8022"
    volumes:
      - .:/app
      - ./secrets/service_account.json:/app/secrets/service_account.json
